import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import WhatsAppButton from "@/components/WhatsAppComponent/WhatsApp";
import ContactModal from "@/Utils/ContactModal";
import { SpeedInsights } from '@vercel/speed-insights/next';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="z-[9998] w-full fixed">
          <Header />
        </div>
          <div className="pt-[101px] w-full">
            {children}
          </div>
          <Footer />
          <WhatsAppButton />
          <ContactModal firstOpenDelay={20000} reopenDelay={80000}/>
           <SpeedInsights />
      </body>
    </html>
  );
}
